In [4]:
import torch
from torch import nn

In [5]:
X = torch.arange(16, dtype=torch.float32).reshape((1,1,4,4))    # start=0, end=16,step为1，返回一维张量，其值介于区间 [start,end]，补偿为step
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [6]:
pool2d = nn.MaxPool2d(3)    # 3表示是3*3的窗口，pytorch种步幅和窗口大小相同，即每个窗口之间没有重叠
pool2d(X)

tensor([[[[10.]]]])

In [13]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)     # padding=1 表示四周都填上一行（一列）,stride=2表示步幅为2
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [14]:
pool2d = nn.MaxPool2d((2,3),padding=(1,1),stride=(2,3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [18]:
X = torch.arange(16, dtype=torch.float32).reshape((1,1,4,4))

X = torch.cat((X,X+1),1)      # 1表示X和X+1横着拼
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [19]:
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])